<Project>
  <!-- MSBuild only includes the first Directory.Build.props, so we need to manually include the root one -->
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
  <PropertyGroup>
    <DebugType>embedded</DebugType>
    <!-- package metadata -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>A dependency manager for .NET with support for NuGet packages and git repositories. Aardvark Platform fork with .NET 10.0 support.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/aardvark-platform/Paket</PackageProjectUrl>
    <PackageIcon>logo.png</PackageIcon>
    <PackageTags>nuget;bundler;F#</PackageTags>
    <Authors>Paket team, Aardvark Platform Team</Authors>
  </PropertyGroup>
</Project>